// Ralph's full media appearances archive — mirrors the "Ralph's Appearances"
// grid that used to live at askralph.com/ralphs-appearances/. Archived and
// self-hosted (images in /public/images/appearances) since askralph.com is
// being retired. `date` is the real publish date (fetched from each source's
// own metadata — iTunes lookup/search API for Apple Podcasts, page meta tags
// elsewhere) so newest/oldest sorting reflects actual chronology, not scrape
// order. `featured` mirrors editorially-notable appearances, used as the
// primary signal for the "Most Popular" sort (tie-broken by date).

export type AppearanceType = "podcast" | "video" | "article";

export interface Appearance {
  slug: string;
  image: string;
  title: string;
  outlet: string;
  url: string;
  type: AppearanceType;
  date: string;
  featured: boolean;
}

export const APPEARANCES: Appearance[] = [
  { slug: "marketwatch-ultra-low-fee-adviser", image: "/images/appearances/marketwatch.webp", title: "'Why wouldn't I?' An Ultra-Low-Fee Adviser at a Large Firm Promised Me a Balanced Portfolio With Market-Beating Returns. Why Go Anywhere Else?", outlet: "MarketWatch", url: "https://www.marketwatch.com/picks/why-wouldnt-i-an-ultra-low-fee-adviser-at-a-large-firm-promised-me-a-balanced-portfolio-with-market-beating-returns-why-go-anywhere-else-9571d568", type: "article", date: "2026-08-05", featured: true },
  { slug: "aol-5-money-moves-scratch", image: "/images/appearances/aol.webp", title: "Finance Experts: 5 Money Moves I'd Make if I Were Starting From Scratch", outlet: "AOL", url: "https://www.aol.com/articles/finance-experts-5-money-moves-140010000.html", type: "article", date: "2026-08-04", featured: true },
  { slug: "aol-5-hard-truths-retirement", image: "/images/appearances/aol.webp", title: "5 Hard Truths About Retirement You Need to Face Before Clocking Out on Your Career", outlet: "AOL", url: "https://www.aol.com/articles/5-hard-truths-retirement-face-100000000.html", type: "article", date: "2026-08-03", featured: true },
  { slug: "aol-80k-upper-middle-class", image: "/images/appearances/aol.webp", title: "10 States Where $80K Gives an Upper-Middle-Class Lifestyle", outlet: "AOL", url: "https://www.aol.com/articles/10-states-where-80k-gives-113009000.html", type: "article", date: "2026-07-30", featured: true },
  { slug: "marketing-against-the-grain", image: "/images/appearances/marketing-against-the-grain.webp", title: "Your Content Strategy Might Be Building the Wrong Thing", outlet: "Marketing Against the Grain", url: "https://marketingagainstthegrain.com/articles/your-content-strategy-might-be-building-the-wrong-thing", type: "article", date: "2026-07-29", featured: true },
  { slug: "aol-raise-most-boring", image: "/images/appearances/aol.webp", title: "Why the Smartest Thing You Can Do With a Raise Is the Most Boring", outlet: "AOL", url: "https://www.aol.com/articles/why-smartest-thing-raise-most-110009000.html", type: "article", date: "2026-07-28", featured: true },
  { slug: "aol-retirees-emergency-fund", image: "/images/appearances/aol.webp", title: "Here's How Much Retirees Should Keep in an Emergency Fund", outlet: "AOL", url: "https://www.aol.com/articles/heres-much-retirees-keep-emergency-123024000.html", type: "article", date: "2026-07-28", featured: true },
  { slug: "howtopodcast-e753", image: "/images/appearances/howtopodcast.webp", title: "How Podcasters Lose Money in Podcasting (E753)", outlet: "The How To Podcast Series", url: "https://podcasts.apple.com/us/podcast/the-how-to-podcast-series-podcast-co-hosts-practical/id1610039000?i=1000777538033", type: "podcast", date: "2026-07-20", featured: false },
  { slug: "aol-boomer-genz-retirement", image: "/images/appearances/aol-boomer-genz-retirement.webp", title: "How Boomer and Gen Z Couples Define Retirement 'Wealth'", outlet: "AOL", url: "https://www.aol.com/finance/boomer-gen-z-couples-define-113005700.html", type: "article", date: "2026-07-11", featured: true },
  { slug: "moneylion-grocery-prices", image: "/images/appearances/moneylion-grocery-prices.webp", title: "Grocery Prices 'Unfair,' Americans Say as Costs Rise — 6 Ways You Can Save Right Now", outlet: "MoneyLion", url: "https://moneylion.com/trending/money/grocery-prices-unfair-americans-costs-rise-save-right-now", type: "article", date: "2026-07-11", featured: true },
  { slug: "podnews-daylight-media-maher", image: "/images/appearances/podnews-daylight-media-maher.webp", title: "Featured in Podnews' Daily Newsletter — Audio? Video? Your Audience Doesn't Care", outlet: "Podnews", url: "https://podnews.net/update/daylight-media-maher", type: "article", date: "2026-07-13", featured: true },
  { slug: "eciks-mid-year-reset", image: "/images/appearances/eciks-mid-year-reset.webp", title: "It's Mid-2026 — Here's How To Refocus Your Savings Goals and Get Back On Track Financially", outlet: "ECIKS.org", url: "https://eciks.org/12669-28619-saving-money-mid-year-reset-2026", type: "article", date: "2026-07-09", featured: false },
  { slug: "moneylion", image: "/images/appearances/moneylion.webp", title: "I'm a Money Expert: Here's How To Use Summer Income To Get $1K Ahead This Year", outlet: "MoneyLion", url: "https://www.moneylion.com/trending/money/im-a-money-expert-how-use-summer-income-get-1k-ahead", type: "article", date: "2026-07-04", featured: true },
  { slug: "aol", image: "/images/appearances/aol.webp", title: "The Mid-Year Budget Reset That Can Save You $500+ Before Fall — a Step-by-Step Guide", outlet: "AOL", url: "https://www.aol.com/articles/mid-budget-reset-save-500-130309000.html", type: "article", date: "2026-07-03", featured: true },
  { slug: "howtopitchapodcast", image: "/images/appearances/howtopitchapodcast.webp", title: "There is Only One Issue - I Do a Solo Show", outlet: "How to Pitch a Podcast", url: "https://podcasts.apple.com/us/podcast/how-to-pitch-a-podcast/id6784521587", type: "podcast", date: "2026-07-02", featured: true },
  { slug: "ceciltaylorministries-episode", image: "/images/appearances/ceciltaylorministries.webp", title: "How Faith and Finances Affect Each Other (S6, E3) — Episode Page", outlet: "Cecil Taylor Ministries Podcast", url: "https://www.ceciltaylorministries.com/podcast/episode/3749dd9f/practical-faith-academy-season-6-episode-3-ralph-estep-jr-how-faith-and-finances-affect-each-other", type: "podcast", date: "2026-06-09", featured: false },
  { slug: "ceciltaylorministries", image: "/images/appearances/ceciltaylorministries.webp", title: "How Faith and Finances Affect Each Other (S6, E3) — Blog Recap", outlet: "Cecil Taylor Ministries Podcast", url: "https://www.ceciltaylorministries.com/post/podcast-blog-s6-e3-ralph-estep-jr-how-faith-and-finances-affect-each-other", type: "podcast", date: "2026-06-09", featured: false },
  { slug: "howtopodcast", image: "/images/appearances/howtopodcast.webp", title: "We Ask Ralph About Podcasting, The Business of Content Creation", outlet: "The How To Podcast Series", url: "https://www.youtube.com/watch?v=ycEpWv-cRzw", type: "video", date: "2026-05-10", featured: true },
  { slug: "lifestoriespodcast", image: "/images/appearances/lifestoriespodcast.webp", title: "Building with Purpose: A Conversation for Content Creators", outlet: "Life Stories Podcast", url: "https://www.youtube.com/watch?v=oKJU0YG7TEk", type: "video", date: "2026-05-07", featured: true },
  { slug: "pmc-lieBrokePodcasters", image: "/images/appearances/podcastingmorningshow.webp", title: "The Lie Keeping Podcasters Broke (Money Monday)", outlet: "Podcasting Morning Show", url: "https://podcasts.apple.com/us/podcast/podcasting-morning-chat/id1728781644?i=1000766097924", type: "podcast", date: "2026-05-04", featured: true },
  { slug: "pmc-firstmoneymistake", image: "/images/appearances/podcastingmorningshow.webp", title: "The First Money Mistake Podcasters Make (Money Mondays)", outlet: "Podcasting Morning Show", url: "https://podcasts.apple.com/us/podcast/podcasting-morning-chat/id1728781644?i=1000762436368", type: "podcast", date: "2026-04-20", featured: true },
  { slug: "pmc-biggestmoneymistake", image: "/images/appearances/podcastingmorningshow.webp", title: "The Biggest Money Mistake Podcasters Make (First Money Mondays)", outlet: "Podcasting Morning Show", url: "https://podcasts.apple.com/us/podcast/podcasting-morning-chat/id1728781644?i=1000756854530", type: "podcast", date: "2026-03-23", featured: false },
  { slug: "podcastingmorningchat", image: "/images/appearances/askralphmedia-logo.webp", title: "Ask Ralph Media, Inc. Announces Podcasting Morning Chat Names Ralph Estep Jr. Co-Executive Producer Alongside Founder Marc Ronick", outlet: "GlobeNewswire", url: "https://www.globenewswire.com/news-release/2026/03/18/3258099/0/en/Ask-Ralph-Media-Inc-Announces-Podcasting-Morning-Chat-Names-Ralph-Estep-Jr-Co-Executive-Producer-Alongside-Founder-Marc-Ronick.html", type: "article", date: "2026-03-18", featured: true },
  { slug: "whenyoulook", image: "/images/appearances/whenyoulook.webp", title: "Our Marriage Was Over… Then This Happened | Ep. 053", outlet: "When You Look", url: "https://www.youtube.com/watch?v=Oop7AiQq-Fw", type: "video", date: "2026-03-18", featured: true },
  { slug: "podcastingforfinancialprofessionals", image: "/images/appearances/podcastingforfinancialprofessionals.webp", title: "Podcast Marketing & Monetization: Maximizing ROI Through Strategic Podcast Production | EP 90", outlet: "Podcasting for Financial Professionals", url: "https://www.youtube.com/watch?v=aCPsEwQWr9g", type: "video", date: "2026-03-12", featured: true },
  { slug: "pmc-sponsorshipgeartax", image: "/images/appearances/podcastingmorningshow.webp", title: "How Free Sponsorship Gear Becomes Taxable Income Overnight", outlet: "Podcasting Morning Show", url: "https://podcasts.apple.com/us/podcast/podcasting-morning-chat/id1728781644?i=1000751763863", type: "podcast", date: "2026-02-26", featured: false },
  { slug: "pmc-5000dollars", image: "/images/appearances/podcastingmorningshow.webp", title: "If You Had $5,000, What Would You Fix First?", outlet: "Podcasting Morning Show", url: "https://podcasts.apple.com/us/podcast/podcasting-morning-chat/id1728781644?i=1000750679631", type: "podcast", date: "2026-02-20", featured: false },
  { slug: "thestorylab", image: "/images/appearances/thestorylab.webp", title: "Content Creator Money Chaos: The 10-Minute System That Saves Your Sanity", outlet: "The Story Lab", url: "https://www.buzzsprout.com/2456528/episodes/18646056", type: "podcast", date: "2026-02-09", featured: true },
  { slug: "youtube-live", image: "/images/appearances/youtube-live.webp", title: "Why Most Creators Struggle With Money (And It's Not a Tax Problem)", outlet: "Social Media News Live", url: "https://www.youtube.com/live/b7plAkMvjWI", type: "video", date: "2026-02-06", featured: true },
  { slug: "newmediashowaudio", image: "/images/appearances/newmediashowaudio.webp", title: "Digital Creator 2026 Money Playbook | #647", outlet: "New Media Show", url: "https://podcasts.apple.com/us/podcast/digital-creator-2026-money-playbook-ralph-estep-jr/id392545649?i=1000746403885", type: "podcast", date: "2026-01-23", featured: true },
  { slug: "1000thepisode", image: "/images/appearances/askralphmedia-logo.webp", title: "Ask Ralph Media Celebrates 1,000th Episode of Financially Confident Christian", outlet: "GlobeNewswire", url: "https://www.globenewswire.com/news-release/2026/01/13/3218137/0/en/Ask-Ralph-Media-Celebrates-1-000th-Episode-of-Financially-Confident-Christian.html", type: "article", date: "2026-01-13", featured: true },
  { slug: "bartellesmoneytalk", image: "/images/appearances/bartellesmoneytalk.webp", title: "Faith, Finances & Freedom: How to Get Your House in Order", outlet: "Bartelle's Money Talk", url: "https://podcasts.apple.com/us/podcast/faith-finances-freedom-how-to-get-your-house-in-order/id1732123565?i=1000738663309", type: "podcast", date: "2025-11-27", featured: true },
  { slug: "doyoureallyneedanllc", image: "/images/appearances/doyoureallyneedanllc.webp", title: "Do You Really Need an LLC for Your Podcast?", outlet: "Podcast Marketing Corner", url: "https://www.podpage.com/pmc/do-you-really-need-an-llc-for-your-podcast/", type: "article", date: "2025-11-18", featured: false },
  { slug: "anexperimentcalledlife", image: "/images/appearances/anexperimentcalledlife.webp", title: "Faith, Family & Finances: A Better Path to Success", outlet: "An Experiment Called Life", url: "https://alextellsjokes.com/podcast/ecl131-faith-family-finances-a-better-path-to-success-ralph-estep-jr/", type: "podcast", date: "2025-11-12", featured: false },
  { slug: "aplegal", image: "/images/appearances/aplegal.webp", title: "Divorce and Financial Chaos: How to Protect Yourself Before It's Late", outlet: "AP Legal Zone", url: "https://podcasts.apple.com/us/podcast/episode-87-divorce-and-financial-chaos-how-to-protect/id1561629475?i=1000735127542", type: "podcast", date: "2025-11-04", featured: false },
  { slug: "thethrivewithinpodcast", image: "/images/appearances/thethrivewithinpodcast.webp", title: "Breaking the Silence of Financial Shame", outlet: "The Thrive Within Podcast", url: "https://www.buzzsprout.com/2506417/episodes/18089210", type: "podcast", date: "2025-10-29", featured: false },
  { slug: "fermenting", image: "/images/appearances/fermenting.webp", title: "Calculating the Ingredients: How to Be a Financially Confident Christian", outlet: "Fermenting: God's Not Done With Me Yet", url: "https://podcasts.apple.com/us/podcast/calculating-the-ingredients-asking-accountant-ralph/id1815595800?i=1000731534722", type: "podcast", date: "2025-10-13", featured: false },
  { slug: "halfwaytosunday", image: "/images/appearances/halfwaytosunday-scarcity-shouts-gratitude-whispers-w-ralph-estep-jr-ep-76-5ta0mhfe.webp", title: "Scarcity Shouts. Gratitude Whispers. (Ep. 76)", outlet: "Halfway to Sunday", url: "https://halfwaytosunday.simplecast.com/episodes/scarcity-shouts-gratitude-whispers-w-ralph-estep-jr-ep-76-5ta0mhFe", type: "podcast", date: "2025-09-24", featured: false },
  { slug: "askralphmedialaunch", image: "/images/appearances/barchart.webp", title: "Ralph Estep Jr Launches Ask Ralph Media to Help Christians Overcome Financial Shame and Build Wealth", outlet: "Barchart", url: "https://www.barchart.com/story/news/34194221/ralph-estep-jr-launches-ask-ralph-media-to-help-christians-overcome-financial-shame-and-build-wealth", type: "article", date: "2025-08-15", featured: false },
  { slug: "powerofman", image: "/images/appearances/powerofman.webp", title: "Power of Man #253 - Christian, Accountant, Author", outlet: "Power of Man", url: "https://podcasts.apple.com/us/podcast/power-of-man-253-christian-accountant-author-ralph-estep/id1591806172?i=1000716670771", type: "podcast", date: "2025-07-10", featured: false },
  { slug: "moneytalk", image: "/images/appearances/podcasts-doing-better-with-money-by-talking-about-it-with.webp", title: "Doing Better with Money By Talking About It", outlet: "Money Talk", url: "https://podcasts.apple.com/pt/podcast/doing-better-with-money-by-talking-about-it-with/id1586659053?i=1000713551925&l=en-GB", type: "podcast", date: "2025-06-19", featured: false },
  { slug: "socialmedianewslive2", image: "/images/appearances/socialmedianewslive.webp", title: "The Creator's Guide to Finances", outlet: "Social Media News Live", url: "https://podcasts.apple.com/us/podcast/the-creators-guide-to-finances/id1549411455?i=1000713171924", type: "podcast", date: "2025-06-17", featured: true },
  { slug: "1000crazyquestions", image: "/images/appearances/1000crazyquestions-e.webp", title: "The Truth, Money & You", outlet: "1000 Crazy Questions", url: "http://www.1000crazyquestions.com/e/the-truth-money-you-wralph-estep/", type: "podcast", date: "2025-06-05", featured: false },
  { slug: "12minuteconvos", image: "/images/appearances/podcasts-ralph-estep-breaking-free-through-faith-and-finance-ep-3987.webp", title: "Ralph Estep Jr.: Breaking Free Through Faith and Finance", outlet: "12 Minute Convos", url: "https://podcasts.apple.com/us/podcast/ralph-estep-breaking-free-through-faith-and-finance-ep-3987/id1098716772?i=1000710847192", type: "podcast", date: "2025-06-02", featured: false },
  { slug: "premieraccountingfirm", image: "/images/appearances/building-the-premier-accounting-firm.webp", title: "Get Lifelong Accounting Clients: Relationship-Based Secrets", outlet: "Building the Premier Accounting Firm", url: "https://podcasts.apple.com/us/podcast/get-lifelong-accounting-clients-relationship-based/id1506023469?i=1000699139789", type: "podcast", date: "2025-03-14", featured: false },
  { slug: "ilaradio", image: "/images/appearances/ila-radio.webp", title: "Faith, Finance, and Freedom Through Purposeful Stewardship", outlet: "ILA Radio", url: "https://podcasts.apple.com/ph/podcast/23-ralph-estep-faith-finance-and-freedom-through/id1766422947?i=1000696744022", type: "podcast", date: "2025-02-28", featured: false },
  { slug: "nofruitpodcast", image: "/images/appearances/nofruitpodcast.webp", title: "Money Management for Couples | S7E8", outlet: "No Fruit Podcast", url: "https://www.spreaker.com/episode/money-management-for-couples-with-ralph-estep-jr-s7e8--64179065", type: "podcast", date: "2025-02-25", featured: false },
  { slug: "pastorsandmoney", image: "/images/appearances/pastorsandmoney-pastors-retirement-planning.webp", title: "Retire with Confidence: Expert Tips for Pastors' Retirement Planning", outlet: "Pastors & Money Podcast", url: "https://pastorsandmoney.com/pastors-retirement-planning/", type: "podcast", date: "2025-02-12", featured: false },
  { slug: "brokeupnotbroken", image: "/images/appearances/brokeupnotbroken.webp", title: "Navigating Financial Education and Tax Strategies in Divorce", outlet: "Broke Up Not Broken", url: "https://podcast.allegiantds.com/episodes/dwVxyQcloVV", type: "podcast", date: "2025-02-04", featured: false },
  { slug: "robertplank", image: "/images/appearances/robertplank-1211-finances-success-faith-ralph-estep-jr.webp", title: "Advocate Financial Evangelism Through Authentic Relationships and Biblical Principles", outlet: "Marketer of the Day", url: "http://www.robertplank.com/1211-finances-success-faith-ralph-estep-jr/", type: "podcast", date: "2024-12-21", featured: false },
  { slug: "walkinvictory", image: "/images/appearances/walkinvictory.webp", title: "Break Free From Financial Stress with 7 Life-Changing Principles", outlet: "Walk in Victory", url: "https://podcasts.apple.com/us/podcast/break-free-from-financial-stress-with-7-life-changing/id1459142845?i=1000678635401", type: "podcast", date: "2024-11-29", featured: false },
  { slug: "practicalprepping", image: "/images/appearances/practicalprepping.webp", title: "Getting Through Christmas Without Going Broke", outlet: "Practical Prepping Radio", url: "https://podcasts.apple.com/us/podcast/getting-through-christmas-without-going-broke/id1537267235?i=1000676584668", type: "podcast", date: "2024-11-12", featured: true },
  { slug: "cfochronicles", image: "/images/appearances/cfochronicles.webp", title: "The Hidden Strategies: Ralph's Insights on Technology and Success in Accounting", outlet: "CFO Chronicles", url: "https://podcasts.apple.com/us/podcast/the-hidden-strategies-ralphs-insights-on-technology/id1760779231?i=1000675192049", type: "podcast", date: "2024-10-31", featured: true },
  { slug: "coupleonukes", image: "/images/appearances/coupleonukes.webp", title: "Faith-Based Finance Coaching: How Ralph Estep Jr. Helps People Escape Financial Bondage", outlet: "Couple on Ukes", url: "https://podcasts.apple.com/us/podcast/faith-based-finance-coaching-how-ralph-estep-helps/id1657865479?i=1000673743760", type: "podcast", date: "2024-10-20", featured: true },
  { slug: "iamrefocusedradio", image: "/images/appearances/iamrefocusedradio.webp", title: "Breaking Free from Paycheck to Paycheck", outlet: "I Am Refocused Radio", url: "https://www.spreaker.com/episode/breaking-free-from-paycheck-to-paycheck-with-ralph-estep-jr--62418150", type: "podcast", date: "2024-10-19", featured: false },
  { slug: "purposeoverprofit", image: "/images/appearances/purposeoverprofit.webp", title: "Purpose Over Profit: Ralph Estep Jr, The Accountant Who Puts Faith First", outlet: "Building the Premier Accounting Firm", url: "https://www.youtube.com/watch?v=N8OoEFIeYUE", type: "video", date: "2024-09-03", featured: false },
  { slug: "wheredidyouseegod", image: "/images/appearances/wheredidyouseegod.webp", title: "Faith and Finances", outlet: "Where Did You See God", url: "https://creators.spotify.com/pod/profile/wheredidyouseegod/episodes/Faith-and-Finances-e2nau71/a-abg2a9p", type: "podcast", date: "2024-08-18", featured: false },
  { slug: "cws", image: "/images/appearances/cws.webp", title: "Ralph Estep, Jr.: My Business Is My Mission Field", outlet: "The CWS Pod", url: "https://www.youtube.com/watch?v=k4IXGJpQ9Is", type: "video", date: "2024-08-14", featured: false },
  { slug: "faithfullyengaged", image: "/images/appearances/faithfullyengaged.webp", title: "Beyond Sunday Mornings: Putting Your Faith into Everyday Financial Actions", outlet: "Faithfully Engaged", url: "https://www.youtube.com/watch?v=AcM2nHur1Kc", type: "video", date: "2024-06-10", featured: false },
  { slug: "weeklywealth", image: "/images/appearances/podcasts-ep-172-ralph-estep-of-the-ask-ralph-podcast.webp", title: "Ralph Estep Jr. of the Ask Ralph Podcast", outlet: "The Weekly Wealth Podcast", url: "https://podcasts.apple.com/us/podcast/ep-172-ralph-estep-of-the-ask-ralph-podcast/id1506823732?i=1000658146521", type: "podcast", date: "2024-06-07", featured: false },
  { slug: "inspiredstewardship", image: "/images/appearances/inspiredstewardship-com-wp-content-uploads-2017-11-1400-1400.webp", title: "Interview with Ralph Estep Jr. About Living Your Faith in Business", outlet: "Inspired Stewardship", url: "https://inspiredstewardship.com/podcast/episode-1435-interview-with-ralph-estep-about-living-your-faith-in-business/", type: "podcast", date: "2024-05-13", featured: false },
  { slug: "coachingcall", image: "/images/appearances/coachingcall.webp", title: "Achieve Success in Today's Changing Economy", outlet: "LinkedIn Coaching Call", url: "https://www.linkedin.com/events/7204433571770515456/", type: "video", date: "2024-05-01", featured: false },
  { slug: "weatheringeconomicstorms", image: "/images/appearances/weatheringeconomicstorms.webp", title: "Weathering Economic Storms: A Preppers Guide to Financial Resilience", outlet: "The Preppers Guide", url: "https://podcasts.apple.com/us/podcast/weathering-economic-storms-a-preppers-guide-to/id1301508993?i=1000652331168", type: "podcast", date: "2024-04-13", featured: true },
  { slug: "financialfreedompodcast", image: "/images/appearances/youtube-watch.webp", title: "Balancing Acts: Finance and Faith", outlet: "Financial Freedom Podcast", url: "https://www.youtube.com/watch?v=mqKffc-MWhU", type: "video", date: "2024-03-07", featured: false },
];
