// Ralph's full media appearances archive — mirrors the "Ralph's Appearances"
// grid that used to live at askralph.com/ralphs-appearances/. Archived and
// self-hosted (images in /public/images/appearances) since askralph.com is
// being retired. `order` preserves the source page's newest-first ordering;
// `featured` mirrors which entries Podpage had flagged as "Featured" there,
// used here as the best available signal for the "Most Popular" sort.

export type AppearanceType = "podcast" | "video" | "article";

export interface Appearance {
  slug: string;
  image: string;
  title: string;
  outlet: string;
  url: string;
  type: AppearanceType;
  order: number;
  featured: boolean;
}

export const APPEARANCES: Appearance[] = [
  { slug: "podcastingmorningchat", image: "/images/appearances/askralphmedia-logo.webp", title: "Ask Ralph Media, Inc. Announces Podcasting Morning Chat Names Ralph Estep Jr. Co-Executive Producer Alongside Founder Marc Ronick", outlet: "GlobeNewswire", url: "https://www.globenewswire.com/news-release/2026/03/18/3258099/0/en/Ask-Ralph-Media-Inc-Announces-Podcasting-Morning-Chat-Names-Ralph-Estep-Jr-Co-Executive-Producer-Alongside-Founder-Marc-Ronick.html", type: "article", order: 0, featured: true },
  { slug: "1000thepisode", image: "/images/appearances/askralphmedia-logo.webp", title: "Ask Ralph Media Celebrates 1,000th Episode of Financially Confident Christian", outlet: "GlobeNewswire", url: "https://www.globenewswire.com/news-release/2026/01/13/3218137/0/en/Ask-Ralph-Media-Celebrates-1-000th-Episode-of-Financially-Confident-Christian.html", type: "article", order: 1, featured: true },
  { slug: "askralphmedialaunch", image: "/images/appearances/barchart.webp", title: "Ralph Estep Jr Launches Ask Ralph Media to Help Christians Overcome Financial Shame and Build Wealth", outlet: "Barchart", url: "https://www.barchart.com/story/news/34194221/ralph-estep-jr-launches-ask-ralph-media-to-help-christians-overcome-financial-shame-and-build-wealth", type: "article", order: 2, featured: false },
  { slug: "ceciltaylorministries", image: "/images/appearances/ceciltaylorministries.webp", title: "How Faith and Finances Affect Each Other (S6, E3)", outlet: "Cecil Taylor Ministries Podcast", url: "https://www.ceciltaylorministries.com/post/podcast-blog-s6-e3-ralph-estep-jr-how-faith-and-finances-affect-each-other", type: "podcast", order: 3, featured: false },
  { slug: "purposeoverprofit", image: "/images/appearances/purposeoverprofit.webp", title: "Purpose Over Profit: Ralph Estep Jr, The Accountant Who Puts Faith First", outlet: "Building the Premier Accounting Firm", url: "https://www.youtube.com/watch?v=N8OoEFIeYUE", type: "video", order: 4, featured: false },
  { slug: "moneylion", image: "/images/appearances/moneylion.webp", title: "I'm a Money Expert: Here's How To Use Summer Income To Get $1K Ahead This Year", outlet: "MoneyLion", url: "https://www.moneylion.com/trending/money/im-a-money-expert-how-use-summer-income-get-1k-ahead", type: "article", order: 5, featured: true },
  { slug: "aol", image: "/images/appearances/aol.webp", title: "The Mid-Year Budget Reset That Can Save You $500+ Before Fall — a Step-by-Step Guide", outlet: "AOL", url: "https://www.aol.com/articles/mid-budget-reset-save-500-130309000.html", type: "article", order: 6, featured: true },
  { slug: "howtopitchapodcast", image: "/images/appearances/howtopitchapodcast.webp", title: "There is Only One Issue - I Do a Solo Show", outlet: "How to Pitch a Podcast", url: "https://podcasts.apple.com/us/podcast/how-to-pitch-a-podcast/id6784521587", type: "podcast", order: 7, featured: true },
  { slug: "howtopodcast", image: "/images/appearances/howtopodcast.webp", title: "We Ask Ralph About Podcasting, The Business of Content Creation", outlet: "The How To Podcast Series", url: "https://www.youtube.com/watch?v=ycEpWv-cRzw", type: "video", order: 8, featured: true },
  { slug: "lifestoriespodcast", image: "/images/appearances/lifestoriespodcast.webp", title: "Building with Purpose: A Conversation for Content Creators", outlet: "Life Stories Podcast", url: "https://www.youtube.com/watch?v=oKJU0YG7TEk", type: "video", order: 9, featured: true },
  { slug: "whenyoulook", image: "/images/appearances/whenyoulook.webp", title: "Our Marriage Was Over… Then This Happened | Ep. 053", outlet: "When You Look", url: "https://www.youtube.com/watch?v=Oop7AiQq-Fw", type: "video", order: 10, featured: true },
  { slug: "podcastingforfinancialprofessionals", image: "/images/appearances/podcastingforfinancialprofessionals.webp", title: "Podcast Marketing & Monetization: Maximizing ROI Through Strategic Podcast Production | EP 90", outlet: "Podcasting for Financial Professionals", url: "https://www.youtube.com/watch?v=aCPsEwQWr9g", type: "video", order: 11, featured: true },
  { slug: "thestorylab", image: "/images/appearances/thestorylab.webp", title: "Content Creator Money Chaos: The 10-Minute System That Saves Your Sanity", outlet: "The Story Lab", url: "https://www.buzzsprout.com/2456528/episodes/18646056", type: "podcast", order: 12, featured: true },
  { slug: "youtube-live", image: "/images/appearances/youtube-live.webp", title: "Why Most Creators Struggle With Money (And It's Not a Tax Problem)", outlet: "Social Media News Live", url: "https://www.youtube.com/live/b7plAkMvjWI", type: "video", order: 13, featured: true },
  { slug: "newmediashowaudio", image: "/images/appearances/newmediashowaudio.webp", title: "Digital Creator 2026 Money Playbook | #647", outlet: "New Media Show", url: "https://podcasts.apple.com/us/podcast/digital-creator-2026-money-playbook-ralph-estep-jr/id392545649?i=1000746403885", type: "podcast", order: 14, featured: true },
  { slug: "bartellesmoneytalk", image: "/images/appearances/bartellesmoneytalk.webp", title: "Faith, Finances & Freedom: How to Get Your House in Order", outlet: "Bartelle's Money Talk", url: "https://podcasts.apple.com/us/podcast/faith-finances-freedom-how-to-get-your-house-in-order/id1732123565?i=1000738663309", type: "podcast", order: 15, featured: true },
  { slug: "weatheringeconomicstorms", image: "/images/appearances/weatheringeconomicstorms.webp", title: "Weathering Economic Storms: A Preppers Guide to Financial Resilience", outlet: "The Preppers Guide", url: "https://podcasts.apple.com/us/podcast/weathering-economic-storms-a-preppers-guide-to/id1301508993?i=1000652331168", type: "podcast", order: 16, featured: true },
  { slug: "doyoureallyneedanllc", image: "/images/appearances/doyoureallyneedanllc.webp", title: "Do You Really Need an LLC for Your Podcast?", outlet: "Podcast Marketing Corner", url: "https://www.podpage.com/pmc/do-you-really-need-an-llc-for-your-podcast/", type: "article", order: 17, featured: false },
  { slug: "anexperimentcalledlife", image: "/images/appearances/anexperimentcalledlife.webp", title: "Faith, Family & Finances: A Better Path to Success", outlet: "An Experiment Called Life", url: "https://alextellsjokes.com/podcast/ecl131-faith-family-finances-a-better-path-to-success-ralph-estep-jr/", type: "podcast", order: 18, featured: false },
  { slug: "aplegal", image: "/images/appearances/aplegal.webp", title: "Divorce and Financial Chaos: How to Protect Yourself Before It's Late", outlet: "AP Legal Zone", url: "https://podcasts.apple.com/us/podcast/episode-87-divorce-and-financial-chaos-how-to-protect/id1561629475?i=1000735127542", type: "podcast", order: 19, featured: false },
  { slug: "thethrivewithinpodcast", image: "/images/appearances/thethrivewithinpodcast.webp", title: "Breaking the Silence of Financial Shame", outlet: "The Thrive Within Podcast", url: "https://www.buzzsprout.com/2506417/episodes/18089210", type: "podcast", order: 20, featured: false },
  { slug: "fermenting", image: "/images/appearances/fermenting.webp", title: "Calculating the Ingredients: How to Be a Financially Confident Christian", outlet: "Fermenting: God's Not Done With Me Yet", url: "https://podcasts.apple.com/us/podcast/calculating-the-ingredients-asking-accountant-ralph/id1815595800?i=1000731534722", type: "podcast", order: 21, featured: false },
  { slug: "halfwaytosunday", image: "/images/appearances/halfwaytosunday-scarcity-shouts-gratitude-whispers-w-ralph-estep-jr-ep-76-5ta0mhfe.webp", title: "Scarcity Shouts. Gratitude Whispers. (Ep. 76)", outlet: "Halfway to Sunday", url: "https://halfwaytosunday.simplecast.com/episodes/scarcity-shouts-gratitude-whispers-w-ralph-estep-jr-ep-76-5ta0mhFe", type: "podcast", order: 22, featured: false },
  { slug: "pastorsandmoney", image: "/images/appearances/pastorsandmoney-pastors-retirement-planning.webp", title: "Retire with Confidence: Expert Tips for Pastors' Retirement Planning", outlet: "Pastors & Money Podcast", url: "https://pastorsandmoney.com/pastors-retirement-planning/", type: "podcast", order: 23, featured: false },
  { slug: "moneytalk", image: "/images/appearances/podcasts-doing-better-with-money-by-talking-about-it-with.webp", title: "Doing Better with Money By Talking About It", outlet: "Money Talk", url: "https://podcasts.apple.com/pt/podcast/doing-better-with-money-by-talking-about-it-with/id1586659053?i=1000713551925&l=en-GB", type: "podcast", order: 24, featured: false },
  { slug: "12minuteconvos", image: "/images/appearances/podcasts-ralph-estep-breaking-free-through-faith-and-finance-ep-3987.webp", title: "Ralph Estep Jr.: Breaking Free Through Faith and Finance", outlet: "12 Minute Convos", url: "https://podcasts.apple.com/us/podcast/ralph-estep-breaking-free-through-faith-and-finance-ep-3987/id1098716772?i=1000710847192", type: "podcast", order: 25, featured: false },
  { slug: "1000crazyquestions", image: "/images/appearances/1000crazyquestions-e.webp", title: "The Truth, Money & You", outlet: "1000 Crazy Questions", url: "http://www.1000crazyquestions.com/e/the-truth-money-you-wralph-estep/", type: "podcast", order: 26, featured: false },
  { slug: "robertplank", image: "/images/appearances/robertplank-1211-finances-success-faith-ralph-estep-jr.webp", title: "Advocate Financial Evangelism Through Authentic Relationships and Biblical Principles", outlet: "Marketer of the Day", url: "http://www.robertplank.com/1211-finances-success-faith-ralph-estep-jr/", type: "podcast", order: 27, featured: false },
  { slug: "weeklywealth", image: "/images/appearances/podcasts-ep-172-ralph-estep-of-the-ask-ralph-podcast.webp", title: "Ralph Estep Jr. of the Ask Ralph Podcast", outlet: "The Weekly Wealth Podcast", url: "https://podcasts.apple.com/us/podcast/ep-172-ralph-estep-of-the-ask-ralph-podcast/id1506823732?i=1000658146521", type: "podcast", order: 28, featured: false },
  { slug: "financialfreedompodcast", image: "/images/appearances/youtube-watch.webp", title: "Balancing Acts: Finance and Faith", outlet: "Financial Freedom Podcast", url: "https://www.youtube.com/watch?v=mqKffc-MWhU", type: "video", order: 29, featured: false },
  { slug: "faithfullyengaged", image: "/images/appearances/faithfullyengaged.webp", title: "Beyond Sunday Mornings: Putting Your Faith into Everyday Financial Actions", outlet: "Faithfully Engaged", url: "https://www.youtube.com/watch?v=AcM2nHur1Kc", type: "video", order: 30, featured: false },
  { slug: "cws", image: "/images/appearances/cws.webp", title: "Ralph Estep, Jr.: My Business Is My Mission Field", outlet: "The CWS Pod", url: "https://www.youtube.com/watch?v=k4IXGJpQ9Is", type: "video", order: 31, featured: false },
  { slug: "inspiredstewardship", image: "/images/appearances/inspiredstewardship-com-wp-content-uploads-2017-11-1400-1400.webp", title: "Interview with Ralph Estep Jr. About Living Your Faith in Business", outlet: "Inspired Stewardship", url: "https://inspiredstewardship.com/podcast/episode-1435-interview-with-ralph-estep-about-living-your-faith-in-business/", type: "podcast", order: 32, featured: false },
  { slug: "powerofman", image: "/images/appearances/powerofman.webp", title: "Power of Man #253 - Christian, Accountant, Author", outlet: "Power of Man", url: "https://podcasts.apple.com/us/podcast/power-of-man-253-christian-accountant-author-ralph-estep/id1591806172?i=1000716670771", type: "podcast", order: 33, featured: false },
  { slug: "nofruitpodcast", image: "/images/appearances/nofruitpodcast.webp", title: "Money Management for Couples | S7E8", outlet: "No Fruit Podcast", url: "https://www.spreaker.com/episode/money-management-for-couples-with-ralph-estep-jr-s7e8--64179065", type: "podcast", order: 34, featured: false },
  { slug: "walkinvictory", image: "/images/appearances/walkinvictory.webp", title: "Break Free From Financial Stress with 7 Life-Changing Principles", outlet: "Walk in Victory", url: "https://podcasts.apple.com/us/podcast/break-free-from-financial-stress-with-7-life-changing/id1459142845?i=1000678635401", type: "podcast", order: 35, featured: false },
  { slug: "brokeupnotbroken", image: "/images/appearances/brokeupnotbroken.webp", title: "Navigating Financial Education and Tax Strategies in Divorce", outlet: "Broke Up Not Broken", url: "https://podcast.allegiantds.com/episodes/dwVxyQcloVV", type: "podcast", order: 36, featured: false },
  { slug: "iamrefocusedradio", image: "/images/appearances/iamrefocusedradio.webp", title: "Breaking Free from Paycheck to Paycheck", outlet: "I Am Refocused Radio", url: "https://www.spreaker.com/episode/breaking-free-from-paycheck-to-paycheck-with-ralph-estep-jr--62418150", type: "podcast", order: 37, featured: false },
  { slug: "cfochronicles", image: "/images/appearances/cfochronicles.webp", title: "The Hidden Strategies: Ralph's Insights on Technology and Success in Accounting", outlet: "CFO Chronicles", url: "https://podcasts.apple.com/us/podcast/the-hidden-strategies-ralphs-insights-on-technology/id1760779231?i=1000675192049", type: "podcast", order: 38, featured: true },
  { slug: "coupleonukes", image: "/images/appearances/coupleonukes.webp", title: "Faith-Based Finance Coaching: How Ralph Estep Jr. Helps People Escape Financial Bondage", outlet: "Couple on Ukes", url: "https://podcasts.apple.com/us/podcast/faith-based-finance-coaching-how-ralph-estep-helps/id1657865479?i=1000673743760", type: "podcast", order: 39, featured: true },
  { slug: "premieraccountingfirm", image: "/images/appearances/building-the-premier-accounting-firm.webp", title: "Get Lifelong Accounting Clients: Relationship-Based Secrets", outlet: "Building the Premier Accounting Firm", url: "https://podcasts.apple.com/us/podcast/get-lifelong-accounting-clients-relationship-based/id1506023469?i=1000699139789", type: "podcast", order: 40, featured: false },
  { slug: "wheredidyouseegod", image: "/images/appearances/wheredidyouseegod.webp", title: "Faith and Finances", outlet: "Where Did You See God", url: "https://creators.spotify.com/pod/profile/wheredidyouseegod/episodes/Faith-and-Finances-e2nau71/a-abg2a9p", type: "podcast", order: 41, featured: false },
  { slug: "coachingcall", image: "/images/appearances/coachingcall.webp", title: "Achieve Success in Today's Changing Economy", outlet: "LinkedIn Coaching Call", url: "https://www.linkedin.com/events/7204433571770515456/", type: "video", order: 42, featured: false },
  { slug: "schoolofpodcasting", image: "/images/appearances/schoolofpodcasting-922.webp", title: "Maximizing Your Podcast's Tax Deductions", outlet: "School of Podcasting", url: "https://www.schoolofpodcasting.net/922", type: "podcast", order: 43, featured: false },
  { slug: "ilaradio", image: "/images/appearances/ila-radio.webp", title: "Faith, Finance, and Freedom Through Purposeful Stewardship", outlet: "ILA Radio", url: "https://podcasts.apple.com/ph/podcast/23-ralph-estep-faith-finance-and-freedom-through/id1766422947?i=1000696744022", type: "podcast", order: 44, featured: false },
  { slug: "socialmedianewslive2", image: "/images/appearances/socialmedianewslive.webp", title: "The Creator's Guide to Finances", outlet: "Social Media News Live", url: "https://podcasts.apple.com/us/podcast/the-creators-guide-to-finances/id1549411455?i=1000713171924", type: "podcast", order: 45, featured: true },
  { slug: "practicalprepping", image: "/images/appearances/practicalprepping.webp", title: "Getting Through Christmas Without Going Broke", outlet: "Practical Prepping Radio", url: "https://podcasts.apple.com/us/podcast/getting-through-christmas-without-going-broke/id1537267235?i=1000676584668", type: "podcast", order: 46, featured: true },
];
